config/routes.rb
Omega::Application.routes.draw do
    #match 'calendars' => 'calendars#index'

	resources :accounts
	  
my_routes = lambda {
  resources :customizations do
    collection do
      put :reset_default
    end
  end
  resources :news_items do
    member do     
    end
    collection do
      get :fetch
      put :like
      put :dislike
      put :delete_keyword
      put :create_keyword
    end
  end
  resources :news_item_sources
  
  resources :calendars do
    resources :events
    resources :shares, :as => :calendar_shares, :module => :calendars
    collection do
      get :administer
    end
    member do
      get :share
    end
  end

  scope "/users/:user_id" do
    resources :calendars
  end


  #  resources :events
    resources :form_builders

  scope :path => 'contacts', :as => 'contact', :module => 'contacts' do
    resources :groups
    resources :households
    resources :organizations
    resources :skills do
      collection do
        get :suggest
      end
    end
	 resources :fields do
    	member do
			get :edit
		end
	 end
    resources :interests

    resources :imports do
      collection do
        match :csv_import_wizard, :to => 'imports#csv_import_wizard', :path => 'wizard/step/:step'
        post :update_csv
        get :undo_import
        get :get_import_data
        get :get_import_mapping
        get :undo_import_finalize
        get :redo_mapping
        get :delete_forever
        get :draft_import
        get :redo_import
        get :redo_import_finalize
      end
    end

  end

  resources :contacts do
    collection do
      get :all
      get :search
      get :list
      get :autocomplete
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end

    member do
      get  :upload
      post :do_upload
    end

    scope :as => 'contact', :module => 'contacts' do
      resources :groups do
        member do
          put :assign
          put :remove
          put :move, :path => 'move/:to_id'
        end
      end
    end
  end


  match 'contacts/:action' => 'contacts#search'

  resources :groups do
    #resources :topics
    member do
      get :space
    end    
  end
  resources :posts
  resources :topics
  resources :groups_requesters
  resources :groups_members do
    collection do
      post :add
      delete :remove
    end
  end
  
  resources :services   
  resources :service_sections
  resources :service_registrations do
    collection do
      post :paypal_return
      get :paypal_cancel_return
    end
  end
  
  resources :roles do
    collection do
      put :restore_role_permission_associations
    end
    member do
      put :update_permission
    end
  end

  resources :assets
  resources :asset_allocations

  resources :payments do
    collection do
      post :ipn_handler
    end
  end

  match 'reports/print_file' => 'reports#print_file'
  match 'reports/show' => 'reports#show'
  resources :reports

  namespace :volunteering do
    resources :positions do
      collection do
        get :scheduler
        get :upcoming
        get :mine
        get :my_time_sheets

        get :skills
        get :interests

        resources :skills, :only => [:index, :edit, :update, :destroy]
        resources :interests, :only => [:index, :edit, :update, :destroy]
      end

      member do
        get :history
      end
    end

    resources :schedules
    resources :days

    resources :records do
      collection do
        get :my_applications
        get :pending
        put :create_volunteer
        get :newest
        get :completed
        get :admin_page
        get :new_volunteer
        get :enroll_volunteers
		  post :create_single
		  put :update_status
        post :create_multiple
		  post :message_volunteer
        get :summary
        get :user_history, :path => 'user_history/:contact_id'
		  get :zip_search
      end

      member do
        get :administer
        get :withdraw
      end
    end

    resources :time_entries do
    	collection do
    		get :all_timesheets
    		get :new_timesheets
    		get :summary
    	end
    end



    root :to => 'volunteering#index', :as => ''
  end

  resources :favorites, :only => [:index, :show] do
    collection do
      match :add,    :path => 'add/*klass/:id',    :as => 'add_to'
      match :remove, :path => 'remove/*klass/:id', :as => 'remove_from'
    end
  end

  namespace :favorites do
    get :of_klass, :path => '*klass'
  end

  resources :uploads do

  end

  resources :images do
    collection do
   	get :edit_logo
   	put :update_logo
   end
  end

  resources :sessions do
    collection do
      delete :destroy
    end

    collection do
      get :token, :path => 'new/:token'
    end
  end

	resources :settings do
		collection do
			put :update
			get :edit
		end
	end

  resources :users do
	 member do
		get :my_page
		put :update_my_page
	 end
    collection do
      get :register, :check_email_uniqueness, :check_username_uniqueness
      post :join, :path => 'register'
      get :autocomplete
      get :role_assignment
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end
  end

  match 'lost_username' => 'users#lost_username'
  match 'lost_password' => 'users#lost_password'

  resources :roles
  resources :permissions, :only => [:index, :show]

  resources :messages, :except => [:edit] do
    collection do
      get :sent
    end

    member do
      get :reply
      get :forward
    end
  end

  root :to => 'home#index'

  scope :path => 'form_builder', :controller => :form_builder do
    get :dispatch_ui_element, :path => 'dispatch_ui_element/:element'
    get :dispatch_element_properties, :path => 'dispatch_element_properties/:element'
  end

  resources :pages, :glob_id => true do
    resources :blocks
    resources :components
  end
  resources :blocks
  resources :components

  scope :module => 'omega' do
    match '*url' => '#not_found'
  end
}

	# This allows us to use the /account_name in development.
	# If we used the subdomain, the account_name would be 
	# limited to the subdomain of your development server. 
	if Rails.env.development? or Rails.env.test?
		scope :path => "/:account_name" do
			my_routes.call
		end
	elsif Rails.env.production?
		my_routes.call
	end

end

app/models/topic.rb
	class Topic < Model
	  belongs_to :post, :dependent=>:destroy
	
	  has_many :groups_topics, :dependent=>:destroy
	  has_many :groups, :through=>:groups_topics
	
	  #validates_length_of :caption, :maximum =>40, :message => "The title can only be 40 characters long"
	  #validates_presence_of :caption
	
	  #accepts_nested_attributes_for :posts
	
	  TOPIC_TYPES = ["announcement", "regular"]
	
	  def is_announcement?
	    topic_type=="announcement"
	  end
	  
	  def popularity
	    post.descendants.count
	  end
	
	  def last_post
	    post.last_post
	  end
	
	  def title
	    post.title
	  end
	
	  def content
	    post.content
	  end
	
	  def author
	    post.author
	  end
	
	  def has_author?(user)
	    post.has_author?(user)
	  end
	
	end

app/controllers/topics_controller.rb
	class TopicsController < Controller
	
	  require_dependency "application_lib.rb"
	  include ApplicationLib
	  
	  respond_to :html, :xml, :json, :js
	
	  def show
	    @group = Group.find(params[:group_id])
	    @topic = Topic.find(params[:id])
	  end
	
	  def destroy
	    @group = Group.find(params[:group_id])
	    @topic = Topic.find(params[:id])
	    @topic.post.destroy
	    
	    render :js => "window.location = '#{space_group_url(@group)}'"
	    return
	  end
	
	end

app/helpers/topics_helper.rb
	module TopicsHelper
	
	  require_dependency "application_lib.rb"
	  include ApplicationLib
	
	  def announcement_sign
	    image_tag "/assets/announcement.png"
	  end    
	
	end

app/views/topics/_dialog_destroy_confirm.html.erb
<div id="topic-destroy-dialog-confirm" class="dialog" title="Delete <%= topic.title %>?">
  <p>
    Are you sure to delete this topic?<br/>
    <strong class="italic"><%= topic.title %></strong>
  </p>
</div>

app/views/topics/_show_bottom_links.html.erb
<div class="right_links">
  <%=  link_to "Back to "+@group.name+" Space", space_group_url(@group), :class=>"operation_button" %>
</div>
<script type="text/javascript">
  $('.operation_button').button({ icons: {primary:'ui-icon-gear'} });
</script>

app/views/topics/_show_page_content.html.erb
<div class="topic_block">
  <div class="topic_created_at">
    <%= @topic.created_at %> created by <%=  link_to @topic.author.name, contact_url(@topic.author) %>
  </div>
  <div class="topic_body round shadow <%= "announcement" if @topic.is_announcement? %>">
    <div class="topic_content">
      <%= @topic.content.strip.length==0 ? blank_sign : @topic.content.html_safe %>
    </div>
    <div class="topic_operation_links operation_links" >
      <div class="left_links">
        <p>
          <% unless current_user.is_anonymous? %>
            <%= om_button(:contact => true, :icon=>'mail-new') do %>
              <%= link_to_function "Reply", "load_dialog_form('#{escape_javascript(render "posts/dialog_new_form", :post=>Post.new(:super_post_id=>@topic.post.id), :is_topic=>false)}', {width:620})", "data-tooltip"=>"Reply this post" %>
            <% end %>
          <% end %>
        </p>
      </div>

      <div class="right_links">
        <p>
          <% if is_admin? || @topic.has_author?(current_user) %>

            <%= om_button(:contact => true, :icon=>'edit') do %>
              <%= link_to_function "Edit", "load_dialog_form('#{escape_javascript(render "posts/dialog_edit_form", :post=>@topic.post, :is_topic=>true)}', {width:620})", "data-tooltip"=>"Edit this topic" %>
            <% end %>

            <%= om_button(:contact => true, :icon=>'delete-icon') do %>
              <%= link_to_function "Delete", "destroy_topic('#{escape_javascript(render "topics/dialog_destroy_confirm", :topic=>@topic)}','#{topic_url(@topic, :group_id=>@group.id)}')", "data-tooltip"=>"Delete this topic" %>
            <% end %>

          <% end %>
        </p>
      </div>
      <br clear="all"/>
    </div>
  </div>

</div>

<% @topic.post.sub_posts.each do |post| %>
  <%= render "posts/show", :post=>post %>
<% end %>


<div class="page_bottom_links">
  <%= render "topics/show_bottom_links" %>
</div>

app/views/topics/_show_page_title.html.erb
<%= @topic.title.html_safe %>


app/views/topics/show.html.erb
<% require_stylesheet 'share.css' %>
<% require_stylesheet 'topic.css' %>
<% require_javascript 'util.js' %>
<% require_javascript 'ui_util.js' %>
<% require_javascript 'post/destroy.js'%>
<% require_javascript 'topic/destroy.js'%>

<div class="content circle-corners-bottom" >
  <div class="heading-main">
    <h1 class="page-content page_title">
      <%= render "show_page_title" %>
    </h1>
  </div>

  <div class="page_content">
    <%= render "show_page_content" %>
  </div>
</div>

app/views/topics/show.js.erb
refresh_page('<%= escape_javascript( render "topics/show_page_title") %>', '<%= escape_javascript( render "topics/show_page_content") %>')