config/routes.rb
Omega::Application.routes.draw do
    #match 'calendars' => 'calendars#index'

	resources :accounts
	  
my_routes = lambda {
  resources :customizations do
    collection do
      put :reset_default
    end
  end
  resources :news_items do
    member do     
    end
    collection do
      get :fetch
      put :like
      put :dislike
      put :delete_keyword
      put :create_keyword
    end
  end
  resources :news_item_sources
  
  resources :calendars do
    resources :events
    resources :shares, :as => :calendar_shares, :module => :calendars
    collection do
      get :administer
    end
    member do
      get :share
    end
  end

  scope "/users/:user_id" do
    resources :calendars
  end


  #  resources :events
    resources :form_builders

  scope :path => 'contacts', :as => 'contact', :module => 'contacts' do
    resources :groups
    resources :households
    resources :organizations
    resources :skills do
      collection do
        get :suggest
      end
    end
	 resources :fields do
    	member do
			get :edit
		end
	 end
    resources :interests

    resources :imports do
      collection do
        match :csv_import_wizard, :to => 'imports#csv_import_wizard', :path => 'wizard/step/:step'
        post :update_csv
        get :undo_import
        get :get_import_data
        get :get_import_mapping
        get :undo_import_finalize
        get :redo_mapping
        get :delete_forever
        get :draft_import
        get :redo_import
        get :redo_import_finalize
      end
    end

  end

  resources :contacts do
    collection do
      get :all
      get :search
      get :list
      get :autocomplete
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end

    member do
      get  :upload
      post :do_upload
    end

    scope :as => 'contact', :module => 'contacts' do
      resources :groups do
        member do
          put :assign
          put :remove
          put :move, :path => 'move/:to_id'
        end
      end
    end
  end


  match 'contacts/:action' => 'contacts#search'

  resources :groups do
    #resources :topics
    member do
      get :space
    end    
  end
  resources :posts
  resources :topics
  resources :groups_requesters
  resources :groups_members do
    collection do
      post :add
      delete :remove
    end
  end
  
  resources :services   
  resources :service_sections
  resources :service_registrations do
    collection do
      post :paypal_return
      get :paypal_cancel_return
    end
  end
  
  resources :roles do
    collection do
      put :restore_role_permission_associations
    end
    member do
      put :update_permission
    end
  end

  resources :assets
  resources :asset_allocations

  resources :payments do
    collection do
      post :ipn_handler
    end
  end

  match 'reports/print_file' => 'reports#print_file'
  match 'reports/show' => 'reports#show'
  resources :reports

  namespace :volunteering do
    resources :positions do
      collection do
        get :scheduler
        get :upcoming
        get :mine
        get :my_time_sheets

        get :skills
        get :interests

        resources :skills, :only => [:index, :edit, :update, :destroy]
        resources :interests, :only => [:index, :edit, :update, :destroy]
      end

      member do
        get :history
      end
    end

    resources :schedules
    resources :days

    resources :records do
      collection do
        get :my_applications
        get :pending
        put :create_volunteer
        get :newest
        get :completed
        get :admin_page
        get :new_volunteer
        get :enroll_volunteers
		  post :create_single
		  put :update_status
        post :create_multiple
		  post :message_volunteer
        get :summary
        get :user_history, :path => 'user_history/:contact_id'
		  get :zip_search
      end

      member do
        get :administer
        get :withdraw
      end
    end

    resources :time_entries do
    	collection do
    		get :all_timesheets
    		get :new_timesheets
    		get :summary
    	end
    end



    root :to => 'volunteering#index', :as => ''
  end

  resources :favorites, :only => [:index, :show] do
    collection do
      match :add,    :path => 'add/*klass/:id',    :as => 'add_to'
      match :remove, :path => 'remove/*klass/:id', :as => 'remove_from'
    end
  end

  namespace :favorites do
    get :of_klass, :path => '*klass'
  end

  resources :uploads do

  end

  resources :images do
    collection do
   	get :edit_logo
   	put :update_logo
   end
  end

  resources :sessions do
    collection do
      delete :destroy
    end

    collection do
      get :token, :path => 'new/:token'
    end
  end

	resources :settings do
		collection do
			put :update
			get :edit
		end
	end

  resources :users do
	 member do
		get :my_page
		put :update_my_page
	 end
    collection do
      get :register, :check_email_uniqueness, :check_username_uniqueness
      post :join, :path => 'register'
      get :autocomplete
      get :role_assignment
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end
  end

  match 'lost_username' => 'users#lost_username'
  match 'lost_password' => 'users#lost_password'

  resources :roles
  resources :permissions, :only => [:index, :show]

  resources :messages, :except => [:edit] do
    collection do
      get :sent
    end

    member do
      get :reply
      get :forward
    end
  end

  root :to => 'home#index'

  scope :path => 'form_builder', :controller => :form_builder do
    get :dispatch_ui_element, :path => 'dispatch_ui_element/:element'
    get :dispatch_element_properties, :path => 'dispatch_element_properties/:element'
  end

  resources :pages, :glob_id => true do
    resources :blocks
    resources :components
  end
  resources :blocks
  resources :components

  scope :module => 'omega' do
    match '*url' => '#not_found'
  end
}

	# This allows us to use the /account_name in development.
	# If we used the subdomain, the account_name would be 
	# limited to the subdomain of your development server. 
	if Rails.env.development? or Rails.env.test?
		scope :path => "/:account_name" do
			my_routes.call
		end
	elsif Rails.env.production?
		my_routes.call
	end

end

app/models/contact/group.rb
	class Contact::Group < Model
	  GROUP_TYPES = %w{Household Organization}
	
	  has_many :group_positions, :dependent => :destroy
	  has_many :contacts, :through => :group_positions
	  
	  has_many :addresses,     :as => :contact, :dependent => :destroy
	  has_many :phone_numbers, :as => :contact, :dependent => :destroy
	
	  accepts_nested_attributes_for :addresses, :phone_numbers,
	                                :reject_if => NestedHelper::REJECT_TEMPLATE, :allow_destroy => true
	
	  scope :with_contact,    lambda { |contact| where('id in (?)',     contact.group_ids) }
	  scope :without_contact, lambda { |contact| where('id not in (?)', contact.group_ids) unless contact.groups.empty? }
	
	  scope :households,    where('group_type = ?', 'Household')
	  scope :organizations, where('group_type = ?', 'Organization')
	
	  validate :group_type, :presence  => true,
	                        :inclusion => { :in => GROUP_TYPES }
	  scope :named, lambda { |name| where('name like ? ', "%#{name}%") }
	
	end

app/models/group.rb
	class Group < Model
	  PERM_ADMIN = 'groups_admin'
	  PERM_VIEW  = 'groups_view'
	
	  ROOT_SUPER_GROUP_ID = "root"
	  NAME_MAX_LENGTH = 100
	
	  belongs_to :super_group, :class_name => "Group"
	  has_many :sub_groups, :class_name => "Group", :foreign_key => "super_group_id", :dependent => :destroy, :order => "name"
	  has_many :groups_members, :dependent=>:destroy
	  has_many :members, :through => :groups_members, :after_add=>:dispose_request
	  has_many :groups_requesters, :dependent=>:destroy
	  has_many :requesters, :through => :groups_requesters
	  has_many :groups_roles, :dependent=>:destroy
	  has_many :roles, :through=>:groups_roles
	  has_many :groups_topics, :dependent=>:destroy
	  has_many :topics, :through=>:groups_topics
	  has_many :groups_uploads, :dependent=>:destroy
	  has_many :uploads, :through=>:groups_uploads
	
	  scope :named, lambda { |name| where(:name=>name) }
	  scope :named_like, lambda { |name| where('name like ? ', "%#{name}%") }
	  scope :without_contact, lambda { |contact| where('id not in (?)', contact.joined_group_ids) unless contact.joined_groups.empty? }
	
	  class << self
	    def open?
	      group_roots.each{|gr|return true if gr.status=="public"}
	      false
	    end
	
	    def group_roots
	      Group.where(:super_group_id => nil).order(:name)
	    end
	    alias_method :root_groups, :group_roots
	
	    #avoid direct iteration for performance
	    def real_public_groups(group=nil)
	      groups = group.nil? ? Group.root_groups : group.sub_groups
	      groups = groups.select{|g| g.is_public? }
	      groups_tmp = groups[0, groups.length]
	      groups_tmp.each{|g| groups.concat(Group.real_public_groups(g))}
	      groups
	    end
	
	    def public_groups(order_by=:name)
	      Group.where(:status=>"public").order(order_by)
	    end
	
	    def private_groups(order_by=:name)
	      Group.where(:status=>"private").order(order_by)
	    end
	
	  end
	
	  ## instance methods
	  def is_root?
	    super_group.nil?
	  end
	
	  def is_end?
	    sub_groups.empty?
	  end
	
	  def is_ancestor_of?(group)
	    return false if is_end? || group.is_root?
	    group.super_group == self ? true : is_ancestor_of?(group.super_group)
	  end
	
	  def is_descendant_of?(group)
	    return false if is_root? || group.is_end?
	    super_group == group ? true : super_group.is_descendant_of?(group)
	  end
	
	  def sibling_groups
	    is_root? ? Group.root_groups : super_group.sub_groups
	  end
	
	  def super_group_id
	    is_root? ? ROOT_SUPER_GROUP_ID : super_group.id
	  end
	
	  def is_real_public?
	    is_root? ? status=="public" : (status=="public" && super_group.is_real_public?)
	  end
	
	  def is_public?
	    status=="public"
	  end
	
	  def is_private?
	    status=="private"
	  end
	
	  # should we consider publish all parent groups?
	  def publish(recursive)
	    transaction do
	      update_attribute("status", "public")
	      sub_groups.each{|g|g.publish(true)} if recursive
	    end
	  end
	
	  def unpublish(recursive)
	    transaction do
	      update_attribute("status", "private")
	      sub_groups.each{|g|g.unpublish(true)} if recursive
	    end
	  end
	
	  def is_blocked?
	    is_blocked
	  end
	
	  def block
	    update_attribute(:is_blocked, true)
	  end
	
	  def unblock
	    update_attribute(:is_blocked, false)
	  end
	
	  def eligible_for_requester?(requester)
	    eligible_for_member?(requester.contact)
	  end
	
	  def eligible_for_member?(member)
	    return true if is_root?
	    super_group_member = GroupsMember.find_by_group_id_and_member_id(super_group.id, member.id)
	    not super_group_member.nil?
	  end
	
	  def accepted_requesters
	    groups_requesters.select{|gr|gr.status=="accepted"}.map(&:requester)
	  end
	
	  def has_leader?(member)
	    groups_member = GroupsMember.find_by_group_id_and_member_id(self.id, member.id)
	    groups_member && groups_member.is_leader?
	  end
	
	  def has_member?(member)
	    not GroupsMember.find_by_group_id_and_member_id(self.id, member.id).nil?
	  end
	
	  def has_requester?(requester)
	    not GroupsRequester.find_by_group_id_and_requester_id(self.id, requester.id).nil?
	  end
	
	  def dispose_request(member)
	    requester = member.user
	    return if requester.nil?
	    groups_requester = GroupsRequester.find_by_group_id_and_requester_id(self.id, requester.id)
	    groups_requester.destroy if groups_requester # cancel pending request, if there is any
	  end
	
	  def available_contacts
	    assigned_members = self.members(:order=>:first_name)
	    self.is_root? ? Contact.all-assigned_members : self.super_group.members-assigned_members
	  end
	  
	  def announcements
	    topics.where(:topic_type=>"announcement").order("updated_at DESC")
	  end
	  
	  def regular_topics
	    topics.where(:topic_type=>"regular").order("updated_at DESC")
	  end
	  
	end
	
	
	

app/controllers/contacts/groups_controller.rb
	class Contacts::GroupsController < Controller
	  respond_to :html, :xml, :js, :json
	  #sub_layout :determine_sub_layout
	
	  before_filter :get_all_contact_groups, :except => [:index]
	
	  #crud_helper Contact::Group, :find => [:assign, :remove]
	#  require_permission Contact::PERM_VIEW
	#  require_permission Contact::PERM_ADMIN, :only => [:new, :edit, :create, :update, :destroy]
	
	  def index
	    if params[:contact_id]
	      @contact = Contact.find(params[:contact_id])
	      @contact_groups = @contact.groups
	    else
	      @contact_groups = Contact::Group.scoped
	    end
	    respond_with(@contact_groups)
	  end
	
	  def show
	    respond_with(@contact_group)
	  end
	
	  def new
	    @contact_group.addresses.build
	    @contact_group.phone_numbers.build
	    respond_with(@contact_group)
	  end
	
	  def edit
	    respond_with(@contact_group)
	  end
	
	  def create
	    respond_with(@contact_group = Contact::Group.create(params[:contact_group]))
	  end
	
	  def update
	    @contact_group.update_attributes(params[:contact_group])
	    respond_with(@contact_group)
	  end
	
	  def destroy
	    @contact_group.destroy
	    respond_with(@contact_group)
	  end
	
	  def assign
	    @contact = Contact.find(params[:contact_id])
	
	    @group_position = @contact.group_positions.create do |gp|
	      gp.group = @contact_group
	      gp.position = params.delete(:position)
	    end
	    respond_with(@group_position)
	  end
	
	  def remove
	    @contact = Contact.find(params[:contact_id])
	
	    @group_positions = @contact.group_positions.where('group_id = ?', @contact_group).destroy_all
	    respond_with(@group_positions)
	  end
	
	  def move
	    @contact = Contact.find(params[:contact_id])
	    @group_position = @contact.group_positions.find_by_group_id!(params[:id])
	    @group_position.group_id = params[:to_id]
	    @group_position.save
	
	    respond_with(@group_position)
	  end
	
	  private
	    def determine_sub_layout
	      case params[:action]
	        when 'show'
	          'contacts/with_groups'
	        else
	          nil
	      end
	    end
	
	    def get_all_contact_groups
	      @contact_groups = Contact::Group.scoped
	    end
	end

app/controllers/groups_controller.rb
	class GroupsController < Controller
	
	  require_dependency "application_lib.rb"
	  include ApplicationLib
	  require_dependency "group_lib.rb"
	  include GroupLib
	  
	  respond_to :html, :xml, :json, :js
	  breadcrumb 'Groups' => :groups
	
	  def index
	    @group_id = params[:group_id]
	    @group = Group.find_by_id(@group_id) unless @group_id.nil? # use find_by_id to return nil in case no record
	
	    # redirect to default index when the target group is missing
	    if @group_id && @group.nil?
	      redirect_to groups_url
	      return
	    end
	
	    session[:super_group_id] = @group.nil? ? (params[:super_group_id] || session[:super_group_id]) : @group.super_group_id
	    initialize_group_objects
	
	    respond_with(@groups)
	  end
	
	  # app-spec for contact module
	  def show
	    group_id = params[:id]
	    @group = Group.find(group_id)
	    @members = @group.members(:order=>:first_name)    
	  end
	
	  def create
	    params_group = params[:group]
	    params_group.merge!({:capacity=>nil}) if params[:group][:capacity]=="unlimited"
	    @creator = params[:creator_id] ? Contact.find(params[:creator_id]) : current_contact
	
	    Group.transaction do
	      @group = Group.create(params_group)
	      GroupsMember.create(:group_id=>@group.id, :member_id=>@creator.id, :position=>"leader")
	    end
	    
	    respond_with(@group) do |format|
	      format.js {redirect_to groups_url(:group_id=>@group.id)}
	    end
	  end
	
	  def update
	    @group = Group.find(params[:id])
	    @type = params[:type]
	    case @type
	      when "publish"
	        @recursive = (params[:recursive]=="true"||params[:recursive]==true) ? true :false
	        @group.publish(@recursive)
	        initialize_group_objects
	      when "unpublish"
	        @recursive = (params[:recursive]=="true"||params[:recursive]==true) ? true :false
	        @group.unpublish(@recursive)
	        initialize_group_objects
	      when "block"
	        @group.block
	      when "unblock"
	        @group.unblock
	      else
	        params_group = params[:group]
	        params_group.merge!({:capacity=>nil}) if params[:group][:capacity]=="unlimited"
	        @group.update_attributes(params_group)
	
	        respond_with(@group) do |format|
	          format.js {redirect_to groups_url(:group_id=>@group.id)}
	        end
	    end
	  end
	
	  def destroy
	    @group = Group.destroy(params[:id])
	    session[:super_group_id] = @group.super_group_id
	    initialize_group_objects
	  end
	
	  def space
	    @group = Group.find(params[:id])
	    @announcements = @group.announcements
	    @regular_topics = @group.regular_topics
	    @topics = @announcements + @regular_topics
	    @new_post = Post.new(:title=>"New Post")
	    @new_post.build_topic
	  end
	
	end

app/helpers/groups_helper.rb
	module GroupsHelper
	
	  require_dependency "application_lib.rb"
	  include ApplicationLib
	  require_dependency "group_lib.rb"
	  include GroupLib
	
	  def group_bread_crumb(group)
	    while not group.nil?
	      html = " > ".html_safe + (link_to group.name, groups_url(:super_group_id=>group.id), :remote=>true) + html
	      group = group.super_group
	    end
	    html = (link_to "All groups", groups_url(:super_group_id=>Group::ROOT_SUPER_GROUP_ID), :remote=>true) + html;
	    html = "<div class='bread_crumb'>".html_safe + "Location: " + html
	    html += "</div>".html_safe
	  end    
	
	end
	

app/views/groups/_dialog_destroy_confirm.html.erb
<div id="group-destroy-dialog-confirm" class="dialog" title="Delete <%= group.name %>?">
  <p>
    Everything related to this group will be lost.<br/>
    Are you sure to delete <strong class="italic"><%= group.name %>?</strong>
  </p>
</div>

app/views/groups/_dialog_edit_form.html.erb
<% super_group ||= group.super_group %>
<div id="group-edit-dialog-form" class="dialog" title="Edit <%= group.name %>">
  <p>
    <%= render "groups/form", :group=>group, :super_group=>super_group %>
  </p>
</div>

app/views/groups/_dialog_update_status_confirm.html.erb
<div id="group-update-status-dialog-confirm" class="dialog" title="Apply to all sub-groups?">
  <p>
    Also apply to all sub-groups?
  </p>
</div>

app/views/groups/_form.html.erb
<%= form_for group, :remote=>true do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :maxlength=>Group::NAME_MAX_LENGTH, :size=>30 %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, :cols=>30, :rows=>3 %>
  </div>

  <div class="field">
    <% options = [["None",nil]].concat(Group.all.map{|g|[g.name, g.id]}) %>
    <% options.delete [group.name, group.id] %>
    <% default_option_value = (super_group ? super_group.id : group.super_group_id) %>

    <%= form.label :super_group_id, "Belongs To" %>
    <%= form.select :super_group_id, options_for_select(options, default_option_value) %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.text_field :capacity, :maxlength=>6, :size=>6, :value=> group.capacity || "unlimited" %>   
  </div>
<% end %>

app/views/groups/_index_list.html.erb
<% group ||= @group %>
<% groups ||= (@groups || []) %>

<% if groups.empty? || (!Group.open? && !is_admin?) %>
  <%= render "groups/index_empty_message" %>
<% else %>
  <div id="groups_accordion">
    <% groups.each do |group| %>
      <% if(is_admin? || group.has_leader?(current_contact) || group.is_public?) %>
        <div id="group_unit_<%= group.id %>" class="group_unit">
          <h3 id="group_head_<%= group.id %>" class="accordion_head group_head<%= group.is_end? ? " group_end" : " group_branch" %>"
              ondblclick="$.ajax({
                              url: '<%= groups_url(:super_group_id=>group.id) %>',
                              dataType:'script'
                            })" >
            <%= render "groups/show_head", :group=>group %>
          </h3>

          <div id="group_body_<%= group.id %>" class="accordion_body group_body" >
            <%= render "groups/show_body", :group=>group %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <script type="text/javascript">
    var index = false;
    <% if group %>
      index = <%= groups.index(group) %>
    <% end %>

    $( "#groups_accordion" ).accordion({
         active: index,
         header: ">div>h3",
         autoHeight: false,
         clearStyle: true,
         navigation: false,
         collapsible: true
    });
  </script>
<% end %>

app/views/groups/_index_search_box.html.erb
<form>
  <input id="search_text" type="text" maxlength="100" size="50" value="Type here to search..." onfocus="$(this).val('')" onblur="$(this).val('Type here to search...')" />
</form>

<script type="text/javascript">
  $( "#search_text" ).autocomplete({
    //  minLength: 2,
    source: <%= raw groups_to_search.to_json %>,
    select: function( event, ui ) {
      $.ajax({
        url: '<%= groups_url %>',
        data: ({"group_id": ui.item.id}),
        dataType: 'script',
        cache: false
      });
    }
  });
</script>

app/views/groups/_show_body.html.erb
<p><%= nl2br group.description %></p>
<br clear="all" />

<div class="announcement_block">
  <% group.announcements.each do |t| %>
    <div class="announcement">
      <div class="topic_type"><%= announcement_sign %></div>
      <div class="topic_title">
        <%=  link_to t.post.title.html_safe, topic_url(t, :group_id=>group.id) %>
      </div>
    </div>
  <% end %>
</div>

<div class="group_operation_links operation_links" >

  <div class="left_links">
    <p>
      <% unless current_user.is_anonymous? %>
        <% group_member = GroupsMember.find_by_group_id_and_member_id(group.id, current_contact.id) %>
        <% if group_member %>
          <% unless group_member.is_leader? %>
            <%= om_button(:contact => true, :icon=>'user-remove') do %>
              <%= link_to_function "Quit", "destroy_group_member('#{escape_javascript(render "groups_members/dialog_destroy_confirm", :group=>group)}', '#{groups_member_url(group_member)}')", "data-tooltip"=>"Quit this group" %>
            <% end %>
          <% end %>          
        <% else %>
          <% group_request = GroupsRequester.find_by_group_id_and_requester_id(group.id, current_user.id) %>
          <% unless group_request.nil? %>

            <% unless group_request.status=="rejected" %>
              <%= om_button(:contact => true, :icon=>'user-remove') do %>
                <%= link_to_function "Withdraw", "destroy_group_request('#{escape_javascript(render "groups_requesters/dialog_destroy_confirm", :group=>group)}', '#{groups_requester_url(group_request)}')", "data-tooltip"=>"Cancel request" %>
              <% end %>
            <% end %>

          <% else %>
            <% if !group.is_blocked? %>
              <%= om_button(:contact => true, :icon=>'user-add') do %>
                <%= link_to_function "Join",
                  "new_group_request('#{escape_javascript(render "groups_requesters/dialog_new_confirm", :group=>group)}')",
                  "data-tooltip"=>"Join this group" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>   
      <% end %>

      <% if group_member || is_admin? %>
        <%= om_button(:contact => true, :icon=>'back') do %>
          <%=  link_to "Space", space_group_url(group), "data-tooltip"=>"Posts and Uploads" %>
        <% end %>
      <% end %>

      <%= om_button(:contact => true, :icon=>'search') do %>
        <%=  link_to "Sub-Groups(#{group.sub_groups.count})", groups_url(:super_group_id=>group.id), :remote=>true, "data-tooltip"=>"View sub-groups in this group" %>
      <% end %>
      
    </p>
  </div>

  <div class="right_links">
    <p>
      <% if is_admin? || group.has_leader?(current_contact) %>

        <%= om_button(:contact => true, :icon=>'mail-new') do %>
          <%=  link_to "Requests", groups_requesters_url(:group_id=>group.id), "data-tooltip"=>"Manage requests" %>
        <% end %>
        <%= om_button(:contact => true, :icon=>'group') do %>
          <%=  link_to "Members", groups_members_url(:group_id=>group.id), "data-tooltip"=>"Manage memberships" %>
        <% end %>

        <% if group.is_private? %>
          <%= om_button(:contact => true, :icon=>'mail-open') do %>
            <% if group.is_end? %>
              <%=  link_to "Publish", group_url(group, :type=>"publish"), :remote=>true, :method=>:put, "data-tooltip"=>"Publish this group" %>
            <% else %>
              <%= link_to_function "Publish", "update_group_status('#{escape_javascript(render "groups/dialog_update_status_confirm")}', '#{group_url(group, :type=>"publish")}')", "data-tooltip"=>"Publish this group" %>
            <% end %>
          <% end %>
        <% elsif group.is_public? %>
          <%= om_button(:contact => true, :icon=>'mail') do %>
            <% if group.is_end? %>
              <%=  link_to "Unpublish", group_url(group, :type=>"unpublish"), :remote=>true, :method=>:put, "data-tooltip"=>"Unpublish this group" %>
            <% else %>
              <%= link_to_function "Unpublish", "update_group_status('#{escape_javascript(render "groups/dialog_update_status_confirm")}', '#{group_url(group, :type=>"unpublish")}')", "data-tooltip"=>"Unpublish this group" %>
            <% end %>
          <% end %>
        <% end %>

        <%= om_button(:contact => true, :icon=>'edit') do %>
          <%= link_to_function "Edit", "edit_group('#{escape_javascript(render "groups/dialog_edit_form", :group=>group)}')", "data-tooltip"=>"Edit this group" %>
        <% end %>

        <%= om_button(:contact => true, :icon=>'delete-icon') do %>
          <%= link_to_function "Delete", "destroy_group('#{escape_javascript(render "groups/dialog_destroy_confirm", :group=>group)}','#{group_url(group)}')", "data-tooltip"=>"Delete this group" %>
        <% end %>

      <% end %>
    </p>
  </div>

</div>

app/views/groups/_show_head.html.erb
<a href="#" class="group_head_link">
  <%= group.name %>
  <% if current_contact %>
    <span id="group_capacity_<%= group.id %>" class="capacity" >
      <%= om_button(:plain => true, :icon => 'user') do %>
        <%= group.members.count.to_s %><%= " / "+group.capacity.to_s if group.capacity%>
      <% end %>
    </span>
   
    <% group_member = GroupsMember.find_by_group_id_and_member_id(group.id, current_contact.id) %>
    <% if group_member %>
      <span id="group_member_position_<%= group_member.id %>" class="member_position" ><%= group_member.position %></span>
    <% else %>
      <% group_request = GroupsRequester.find_by_group_id_and_requester_id(group.id, current_user.id) %>
      <% if group_request %>
        <span id="group_request_status_<%= group_request.id %>" class="request_status" ><%= group_request.status %></span>
      <% end %>
    <% end %>
    

  <% end %>
</a>

app/views/groups/_space_bottom_links.html.erb
<div class="left_links">
  <%= link_to_function "New", "load_dialog_form('#{escape_javascript(render "posts/dialog_new_form", :post=>@new_post, :is_topic=>true)}', {width:620})", :class=>"operation_button" %>
</div>
<div class="right_links">
  <%=  link_to "Back to "+@group.name, groups_url(:group_id=>@group.id), :class=>"operation_button" %>
</div>
<script type="text/javascript">
  $('.operation_button').button({ icons: {primary:'ui-icon-gear'} });
</script>

app/views/groups/_space_page_title.html.erb
Space of <%= @group.name %>


app/views/groups/destroy.js.erb
$("#group_head_<%= @group.id %>").hide('slow', function(){ $(this).remove(); } )
$("#group_body_<%= @group.id %>").hide('slow', function(){
  $(this).remove();
  <% if @groups.empty? %>
   $(".groups_list").html("<%= escape_javascript( render "index_empty_message") %>")
  <% end %>
})

$(".tipsy").remove();

app/views/groups/index.js.erb
$(".page_title").html("<%= escape_javascript( render "index_page_title") %>")
$(".page_content").html("<%= escape_javascript( render "index_page_content") %>")

$(".tipsy").remove();