config/routes.rb
Omega::Application.routes.draw do
    #match 'calendars' => 'calendars#index'

	resources :accounts
	  
my_routes = lambda {
  resources :customizations do
    collection do
      put :reset_default
    end
  end
  resources :news_items do
    member do     
    end
    collection do
      get :fetch
      put :like
      put :dislike
      put :delete_keyword
      put :create_keyword
    end
  end
  resources :news_item_sources
  
  resources :calendars do
    resources :events
    resources :shares, :as => :calendar_shares, :module => :calendars
    collection do
      get :administer
    end
    member do
      get :share
    end
  end

  scope "/users/:user_id" do
    resources :calendars
  end


  #  resources :events
    resources :form_builders

  scope :path => 'contacts', :as => 'contact', :module => 'contacts' do
    resources :groups
    resources :households
    resources :organizations
    resources :skills do
      collection do
        get :suggest
      end
    end
	 resources :fields do
    	member do
			get :edit
		end
	 end
    resources :interests

    resources :imports do
      collection do
        match :csv_import_wizard, :to => 'imports#csv_import_wizard', :path => 'wizard/step/:step'
        post :update_csv
        get :undo_import
        get :get_import_data
        get :get_import_mapping
        get :undo_import_finalize
        get :redo_mapping
        get :delete_forever
        get :draft_import
        get :redo_import
        get :redo_import_finalize
      end
    end

  end

  resources :contacts do
    collection do
      get :all
      get :search
      get :list
      get :autocomplete
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end

    member do
      get  :upload
      post :do_upload
    end

    scope :as => 'contact', :module => 'contacts' do
      resources :groups do
        member do
          put :assign
          put :remove
          put :move, :path => 'move/:to_id'
        end
      end
    end
  end


  match 'contacts/:action' => 'contacts#search'

  resources :groups do
    #resources :topics
    member do
      get :space
    end    
  end
  resources :posts
  resources :topics
  resources :groups_requesters
  resources :groups_members do
    collection do
      post :add
      delete :remove
    end
  end
  
  resources :services   
  resources :service_sections
  resources :service_registrations do
    collection do
      post :paypal_return
      get :paypal_cancel_return
    end
  end
  
  resources :roles do
    collection do
      put :restore_role_permission_associations
    end
    member do
      put :update_permission
    end
  end

  resources :assets
  resources :asset_allocations

  resources :payments do
    collection do
      post :ipn_handler
    end
  end

  match 'reports/print_file' => 'reports#print_file'
  match 'reports/show' => 'reports#show'
  resources :reports

  namespace :volunteering do
    resources :positions do
      collection do
        get :scheduler
        get :upcoming
        get :mine
        get :my_time_sheets

        get :skills
        get :interests

        resources :skills, :only => [:index, :edit, :update, :destroy]
        resources :interests, :only => [:index, :edit, :update, :destroy]
      end

      member do
        get :history
      end
    end

    resources :schedules
    resources :days

    resources :records do
      collection do
        get :my_applications
        get :pending
        put :create_volunteer
        get :newest
        get :completed
        get :admin_page
        get :new_volunteer
        get :enroll_volunteers
		  post :create_single
		  put :update_status
        post :create_multiple
		  post :message_volunteer
        get :summary
        get :user_history, :path => 'user_history/:contact_id'
		  get :zip_search
      end

      member do
        get :administer
        get :withdraw
      end
    end

    resources :time_entries do
    	collection do
    		get :all_timesheets
    		get :new_timesheets
    		get :summary
    	end
    end



    root :to => 'volunteering#index', :as => ''
  end

  resources :favorites, :only => [:index, :show] do
    collection do
      match :add,    :path => 'add/*klass/:id',    :as => 'add_to'
      match :remove, :path => 'remove/*klass/:id', :as => 'remove_from'
    end
  end

  namespace :favorites do
    get :of_klass, :path => '*klass'
  end

  resources :uploads do

  end

  resources :images do
    collection do
   	get :edit_logo
   	put :update_logo
   end
  end

  resources :sessions do
    collection do
      delete :destroy
    end

    collection do
      get :token, :path => 'new/:token'
    end
  end

	resources :settings do
		collection do
			put :update
			get :edit
		end
	end

  resources :users do
	 member do
		get :my_page
		put :update_my_page
	 end
    collection do
      get :register, :check_email_uniqueness, :check_username_uniqueness
      post :join, :path => 'register'
      get :autocomplete
      get :role_assignment
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end
  end

  match 'lost_username' => 'users#lost_username'
  match 'lost_password' => 'users#lost_password'

  resources :roles
  resources :permissions, :only => [:index, :show]

  resources :messages, :except => [:edit] do
    collection do
      get :sent
    end

    member do
      get :reply
      get :forward
    end
  end

  root :to => 'home#index'

  scope :path => 'form_builder', :controller => :form_builder do
    get :dispatch_ui_element, :path => 'dispatch_ui_element/:element'
    get :dispatch_element_properties, :path => 'dispatch_element_properties/:element'
  end

  resources :pages, :glob_id => true do
    resources :blocks
    resources :components
  end
  resources :blocks
  resources :components

  scope :module => 'omega' do
    match '*url' => '#not_found'
  end
}

	# This allows us to use the /account_name in development.
	# If we used the subdomain, the account_name would be 
	# limited to the subdomain of your development server. 
	if Rails.env.development? or Rails.env.test?
		scope :path => "/:account_name" do
			my_routes.call
		end
	elsif Rails.env.production?
		my_routes.call
	end

end

app/models/volunteering/day.rb
	class Volunteering::Day < Model
	
	  belongs_to :schedule
	
	
	end

app/controllers/volunteering/days_controller.rb
	class Volunteering::DaysController < Controller
	  respond_to :html, :xml, :json, :js
	  require_permission Volunteering::PERM_VIEW
	  require_permission Volunteering::PERM_ADMIN, :only => [:new, :edit, :create, :update, :destroy]
	
	  def index
	      @days = Volunteering::Schedule::Day.all
	      respond_with(@days)
	    end
	
	    def show
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      respond_with(@day)
	    end
	
	    def new
	      @day = Volunteering::Schedule::Day.new
	      respond_with(@day)
	    end
	
	    def edit
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      respond_with(@day)
	    end
	
	    def create
	      @day = Volunteering::Schedule::Day.create(params[:volunteering_schedule_day])
	      respond_with(@day)
	    end
	
	    def update
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      respond_with(@day)
	    end
	
	    def destroy
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      @day.destroy
	           
	    end
	  end

app/controllers/volunteering/interests_controller.rb
	class Volunteering::InterestsController < Controller
	  respond_to :html, :json
	
	  def index
	    @interests = Contact::Interest.scoped
	
	    @interests = @interests.where("name LIKE ?", params[:q] + '%') if params[:q]
	
	    respond_with(@interests) do |format|
	      format.json { render :json => @interests.map { |s| { :id => s.name, :name => s.name } } }
	    end
	  end
	end

app/controllers/volunteering/positions_controller.rb
	class Volunteering::PositionsController < Controller
	  respond_to :html, :xml, :json, :js
	  require 'zipcodr'
	
	  require_permission Volunteering::PERM_VIEW
	  require_permission Volunteering::PERM_ADMIN, :only => [:new, :edit, :create, :update, :destroy]
	
	  before_filter :get_positions, :only => [:index, :upcoming, :skills, :interests]
	  before_filter :get_my_positions, :only => [:mine]
	  before_filter :get_skills, :only => [:index, :upcoming, :skills, :mine]
	  before_filter :get_interests, :only => [:index, :upcoming, :interests, :mine]
	  before_filter :sort, :only => [:index]
	
	  breadcrumb 'Volunteering' => :volunteering
	  breadcrumb 'Positions' => :volunteering_positions
	
	
	  def index
	    @positions = @positions.paginate(:page => params[:page], :per_page => Volunteering::Position::MAX_POSITIONS_PER_PAGE)
      #fetch skills and interests of contacts and return array of unique elements with the number of occurrences
      #this is used in the tag cloud feature
      skills = Contact::Skill.all.map { |r| r.name.to_s.downcase }
      interests = Contact::Interest.all.map { |r| r.name.to_s.downcase }
      @tags = (skills + interests).inject({}) { |r, e| r[e] = r[e].nil? ? 1 : r[e]+1; r }.flatten(0)
	    respond_with(@positions, @tags)
	  end
	
	  def upcoming
	    @positions = @positions.where('start is not null').order('start ASC')
	    @positions = @positions.paginate(:page => params[:page], :per_page => Volunteering::Position::MAX_POSITIONS_PER_PAGE)
	    breadcrumb 'Upcoming Positions' => :upcoming_volunteering_positions
	    respond_with(@positions)
	  end
	
	  def show
	    @position = Volunteering::Position.find(params[:id])
	    breadcrumb @position.name => volunteering_position_path(@position)
	    respond_with(@position)
	  end
	
	  def edit
	    @position = Volunteering::Position.find(params[:id])
	    fix_model_to_view
		 @contact_assignment = @position.contacts.count > 0 ? 'existing' : 'none'
	    respond_with(@position)
	  end
	
	  def new
	    @position = Volunteering::Position.new
	    fix_model_to_view
		 @contact_assignment = 'new'
	    respond_with(@position)
	  end
	
	  def create
		 @contact_assignment = params[:contact_assignment] # Do this in case the validation fails and @position is reloaded.
		 fix_view_to_model
		 #field_positions = params[:volunteering_position].delete(:contact_field_volunteering_position_id)
		 field_ids = params[:volunteering_position].delete(:contact_fields)
		 @position = Volunteering::Position.new(params[:volunteering_position])
		
	 	 #@field.update_positions(field_positions)
	 	 fields = Array.new
		 field_ids.each { |key, id| fields << Contact::Field.find(id) } if !field_ids.nil?
		 @position.contact_fields = fields
		
		 if @position.save
			@position.update_attributes(:end => @position.correct_end_date) if !@position.recurrent
			# Do this after position so that it is assigned an ID.
			#field_positions = @position.id.to_s if field_positions.to_i == 0
		  	respond_with(@position)
		 else
			reset_view_if_error
		   respond_with(@position)
		 end
	  end
	
	  def update
	    fix_view_to_model
	    @position = Volunteering::Position.find(params[:id])
		 @contact_assignment = params[:contact_assignment] # Do this in case the validation fails and @position is reloaded.
	
		 field_ids = params[:volunteering_position].delete(:contact_fields)
		 fields = Array.new
		 if not field_ids.nil?
		 	field_ids.each { |key, id| fields << Contact::Field.find(id) }
		 end
		 @position.contact_fields = fields
	
	    @position.update_attributes(params[:volunteering_position])
	    fix_model_to_view
	    respond_with(@position)
	  end
	
	  def destroy
	    @position = Volunteering::Position.find(params[:id])
	    @position.destroy
	    respond_with(@position)
	  end
	
	  def skills
	    @positions = @positions.paginate(:page => params[:page], :per_page => Volunteering::Position::MAX_POSITIONS_PER_PAGE)
	      breadcrumb 'Skills' => 'skills'
	    render :index
	  end
	
	  def interests
	    @positions = @positions.paginate(:page => params[:page], :per_page => Volunteering::Position::MAX_POSITIONS_PER_PAGE)
	     breadcrumb 'Interests' => 'interests'
	    
	    render :index
	  end
	
	  def mine
	    @postions = Array.new
	    
	    @my_records = Volunteering::Record.where('contact_id = ? and action = ?', Contact.for(current_user), "Accepted")
	    @my_records.each do |r|
	    	@positions << Volunteering::Position.find(r.position_id) 
	    end
	    
	    @positions = @positions.paginate(:page => params[:page], :per_page => Volunteering::Position::MAX_POSITIONS_PER_PAGE)
	
	    breadcrumb 'My Positions' => :mine_volunteering_positions
	  end
	
	  def my_time_sheets
	    @entry_days = Volunteering::TimeEntry::Day.all
	    @timesheets = Array.new
	    @records = Volunteering::Record.find_all_by_contact_id(Contact.for(current_user))
	    @records.each do |r|
	      @timesheets << Volunteering::TimeEntry.find_all_by_record_id(r.id)
	    end
	    breadcrumb 'My Time Sheets' => :my_time_sheets_volunteering_positions
	  end
	
	  def history
	    @position = Volunteering::Position.find(params[:id])
	    @records = @position.records
	    @records = @records.paginate(:page => params[:page], :per_page => Volunteering::Record::MAX_RECORDS_PER_PAGE)
	    respond_with(@records)
	  end
	
	  private
	  
	  def get_positions
	    @positions = Volunteering::Position.includes(:skills, :records).order
	
	    if skills = params[:skills].try(:split, '+')
	      @positions = @positions.select('`volunteering_positions`.*, count(`contact_skills`.`id`) as s_count').
	              joins(:skills).
	              where('contact_skills.name IN (?)', skills).
	              group("`volunteering_positions`.`id` HAVING `s_count` = #{skills.size}")
	    end
	
	    if interests = params[:interests].try(:split, '+')
	      @positions = @positions.select('`volunteering_positions`.*, count(`contact_interests`.`id`) as i_count').
	              joins(:interests).
	              where('contact_interests.name IN (?)', interests).
	              group("`volunteering_positions`.`id` HAVING `i_count` = #{interests.size}")
	    end
	  end
	
	  def get_my_positions
	    @positions = Volunteering::Position.joins(:records).
	            where('volunteering_records.contact_id = ?', Contact.for(current_user)).
	            where('volunteering_records.action = ?', 'accept')
	  end
	
	  def get_skills
	    @skills = Volunteering::Position.where(:id => @positions.map(&:id)).
	            joins(:skills).
	            group('contact_skills.name').
	            select('contact_skills.*, count(*) AS count').
	            order('count desc').limit(20)
	
	    if @skills_tags = params[:skills].try(:split, '+')
	      @skills_tags.each do |skill|
	        @skills = @skills.where('contact_skills.name != ?', skill)
	      end
	    end
	  end
	
	  def get_interests
	    @interests = Volunteering::Position.where(:id => @positions.map(&:id)).
	            joins(:interests).
	            group('contact_interests.name').
	            select('contact_interests.*, count(*) as count').
	            order('count desc').limit(10)
	
	    if @interests_tags = params[:interests].try(:split, '+')
	      @interests_tags.each do |interest|
	        @interests = @interests.where('contact_interests.name != ?', interest)
	      end
	    end
	  end
	
	  SORT_KEYS = ['name']
	  SORT_DIRECTIONS = ['asc', 'desc']
	
	  def sort
	    @positions = Volunteering::Position.scoped
	    params.each do |attr, direction|
	      next unless SORT_KEYS.include?(attr) and SORT_DIRECTIONS.include?(direction)
	      @positions = @positions.order("#{attr} #{direction}")
	    end
	  end
	
	  def fix_view_to_model
	    case params[:contact_assignment]
	      when 'existing'
	        params[:volunteering_position].delete(:contacts_attributes)
	      when 'new'
	        params[:volunteering_position].delete(:contact_ids)
	      when 'none'
	        params[:volunteering_position].delete(:contact_ids)
	        params[:volunteering_position].delete(:contacts_attributes)
	    end
	
	    if contact_ids = params[:volunteering_position][:contact_ids]
	      params[:volunteering_position][:contact_ids] = JSON.parse(contact_ids)
	    end
	
	    if schedule = params[:volunteering_position].delete(:schedule_attributes)
	      case schedule[:schedule_type]
	        when 'daily'
	          params[:volunteering_position][:schedule_attributes] = schedule[:daily]
	          params[:volunteering_position][:schedule_attributes][:schedule_type] = 'daily'
	
	          if params[:daily_type] == 'every_week_day'
	            params[:volunteering_position][:schedule_attributes][:value] = 'weekday'
	          end
	
	        when 'weekly'
	          params[:volunteering_position][:schedule_attributes] = schedule[:weekly]
	          params[:volunteering_position][:schedule_attributes][:schedule_type] = 'weekly'
	          params[:volunteering_position][:schedule_attributes][:start_time] = '00:00'
	          params[:volunteering_position][:schedule_attributes][:end_time] = '00:00'
	      end
	    end
	  end
	
	  def fix_model_to_view
		 @positions = Volunteering::Position.find(:all).unshift(Volunteering::Position::CollectionWithAll.new, Volunteering::Position::CollectionWithCurrentPosition.new)
		 @new_field = Contact::Field.new
	
	    @position.build_event_source unless @position.event_source
	
	    @position.contacts.build do |c|
	      c.phone_numbers.build
	    end if @position.contacts.empty?
	
	    @position.build_schedule unless @position.schedule
	
	    ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].each do |day|
	      @position.schedule.days.build(:day => day) unless @position.schedule.days.any? { |d| d.day == day }
	    end
	  end
	
	  def reset_view_if_error
		 @positions = Volunteering::Position.find(:all).unshift(Volunteering::Position::CollectionWithAll.new, Volunteering::Position::CollectionWithCurrentPosition.new)

app/views/volunteering/time_entries/_form.html.erb
<%# javascript_include_tag 'new_time_entry' %>
<% require_javascript 'thirdParty/jquery.timepicker', 'time_entry' %>

<p class="time_entries">
	Select week: <%= text_field_tag 'volunteering_time_entry_week', nil, :class => 'datepickr', :name => 'volunteering_time_entry[week]' %>
</p>

<div id='record_hours'>
	<%= render 'record_hours' %>
</div>

<script type="text/javascript">

	$(function(){
		$( '#volunteering_time_entry_week' ).change(function(){
			var week = $( '#volunteering_time_entry_week' ).attr( 'value' );
			var contact_id = $( 'select#contact_id' ).attr( 'value' );
			var record_id = $( 'select#volunteering_time_entry_record_id' ).attr( 'value' );
			$.ajax({
				url: "<%= new_volunteering_time_entry_url(:id => @record)%>",
				type: "GET",
				data: {contact_id:contact_id, record_id:record_id, week:week},
				dataType: 'script',
				cache: false
			});
		});
	});

</script>

app/views/volunteering/time_entries/_new_timesheets.html.erb
   
      <%= form_tag :action=> 'create' do %>


        <table class="width-100 clear" id="records-table">
    			<thead>
    				<tr>
      					<th class="ui-state-default">
      						Volunteer </th>
      					<th class="ui-state-default">Mon</th>
      					<th class="ui-state-default">Tue</th>
      					<th class="ui-state-default">Wed</th>
      					<th class="ui-state-default">Thurs</th>
      					<th class="ui-state-default">Fri</th>
      					<th class="ui-state-default">Sat</th>
     					<th class="ui-state-default">Sun</th>

    				</tr>
    			</thead>
   
            
    		
    	<% @entries.each_with_index do |entry, index| %>

    	<%= fields_for "entries[#{index}]", entry do |f| %>

          <p>

         <%= f.hidden_field :week, :value => start %>
     
          </p>

    
    	<%= f.hidden_field :record_id, :value =>  entry.record_id %>
    
      	 	<%= render 'record_row', :entry => entry, :f => f, :start => start %>
    
    	<%end%>
    	<% end %> 
    	
    	</table>  

    	</p>
   	 	<p>
    	<%= om_button(:icon=>'save') do %>
        	<%= submit_tag "Save" %>
   	 	<% end %>

    	</p>

		<% end %>


       

app/views/volunteering/time_entries/_record_hours.html.erb
<%= form_for @entry do |f| %>
   <% hours_errors = [] %>
   <%= errors_for_form @entry %>
   <%= f.hidden_field :record_id %>
	<%= f.hidden_field :week %>

	<table id="record_hours_options">
		<tr>
			<td>
				<% if current_user.has_permission? Volunteering::PERM_ADMIN %>
					User: <%= collection_select :contact, :id, @contacts, :id, :full_name %>
				<% elsif !current_user.has_permission? Volunteering::PERM_ADMIN %>
					User: <strong> <%= current_user.first_name %> </strong>
				<% end %>
			</td>
	
			<td id='select_position_options'>
				Position: <%= f.collection_select :record_id, @records, :id, :position_name %>  
			</td>
		</tr>
	</table>
	
	
	<table class="width-100 time_entries">
		<tr>
	     	<% @entry.days.each_with_index do |ed| %>
	        	<%= f.fields_for "days", ed do |d| %>
	           	<% day = d.object %>
	            <% hours_errors << day.errors unless day.errors.empty? %>
	            <td> <%= d.hidden_field :day %> <%= ed.day %> </td>
	            <td>
						<%= d.text_field :hours, :class => 'inputSmall'%>
						<%= hours_errors.size unless day.errors.empty? %>
	            </td>
	         <% end %>
	      <% end %>
	   </tr>
	</table>

    <% unless hours_errors.empty? %>
        <% hours_errors.each_with_index do |hour_errors, i| %>
            <%= debug hour_errors.full_messages %><%= i + 1 %>
        <% end %>
    <% end %>

	 <div id='record_hours_submit'>
		<%= om_button(:icon=>'save') do %>
        <%= f.submit "Save" %>
		<% end %>
	 </div>

<% end %>

<script type="text/javascript">

	$(function(){
		$( '#record_hours_options' ).delegate( 'select', 'change', function(){
			var week = $( '#volunteering_time_entry_week' ).attr( 'value' );
			var contact_id = $( 'select#contact_id' ).attr( 'value' );
			var record_id = $( 'select#volunteering_time_entry_record_id' ).attr( 'value' );
			$.ajax({
				url: "<%= new_volunteering_time_entry_url(:id => @record)%>",
				type: "GET",
				data: {contact_id:contact_id, record_id:record_id, week:week},
				dataType: 'script',
				cache: false
			});
		});
	});

</script>

app/views/volunteering/time_entries/_record_row.html.erb

        
        <%unless entry.nil? %>
        
        <tr id="record-<%= entry.record_id %>">
          <%= f.hidden_field :week, :value => start %>   
    				<%= f.hidden_field :record_id, :value => entry.record_id %>
          <td> <%=Contact.find(Volunteering::Record.find(entry.record_id).contact_id).first_name%></td>
          
          <%entry.days.each_with_index do |ed| %>
          <%= f.fields_for "days", ed do |d| %>
                <% day = d.object %>
                <% hours_errors << day.errors unless day.errors.empty? %>

                <%= d.hidden_field :id%>
                <%= d.hidden_field :day, :value => day.day%>
                <td>
                  <%= d.text_field :hours, :class => 'inputSmall'%>
                  <%= hours_errors.size unless day.errors.empty? %>
                </td>
                
          <% end %>
      	<% end %>
      	
        
        </tr>
        
   <%end%>

app/views/volunteering/time_entries/_timesheets_table.html.erb
	   <table class="time_entries clear width-100" id="records-table">
    		<thead>
    			<tr>
     				<th>Volunteer</th>
     				<th>Event</th>
					<th>Week</th>
     				<th>Mon</th>
     				<th>Tue</th>
     				<th>Wed</th>
     				<th>Thurs</th>
     				<th>Fri</th>
     				<th>Sat</th>
     				<th>Sun</th>
    			</tr>
    		</thead>

     		<% entries.each do |entry| %>
    	      <tr id="record-<%= entry.record.id %>" ui-data="<%=entry.id%>" data-tooltip="View" >
                <td> <%= Contact.find(Volunteering::Record.find(entry.record_id).contact_id).first_name %> </td>
					 <td> <%= Volunteering::Position.find(entry.record.position.id).name %> </td>
					 <td> <%= entry.week %> </td>
                <%entry.days.each do |d|%>
                 	<td>
                 		<%= d.hours %>
                	</td>
            	<%end%>
            </tr>
     		<% end %>   
 		</table>  

<script type="text/javascript">
	$(function(){
		$( "table.time_entries" ).delegate( 'tr', 'click', function(){
			var time_entry_id = $( this ).attr( 'ui-data' );
			$.ajax({
				url: "<%= new_volunteering_time_entry_url(:id => @record)%>",
				type: "GET",
				data: {time_entry_id:time_entry_id},
				dataType: 'script',
				cache: false
			});
		});
	});
</script>

app/views/volunteering/time_entries/new.html.erb
<% require_javascript 'omega_volunteering_records' %>
<% require_stylesheet 'omega_volunteering', 'thirdParty/jquery.dataTables.jui.css' %>

<h1 class="page-content corners-top"> Record Hours </h1>

<div class="page-content corners-bottom">
	<%= render 'form' %>
	<br /><br /><br />
	<% if current_user.has_permission? Volunteering::PERM_ADMIN %>
		<%= render 'timesheets_table', :entries => Volunteering::TimeEntry.all %>
	<% elsif !current_user.has_permission? Volunteering::PERM_ADMIN %>
		<%= render 'timesheets_table', :entries => @entries %>
	<% end %>
</div>

app/views/volunteering/time_entries/new.js.erb
$( '#record_hours' ).html("<%= escape_javascript( render 'record_hours' ) %>");
var week = $( '#volunteering_time_entry_week' ).attr( 'value' );
$( 'div#record_hours input#volunteering_time_entry_week' ).val(week);

app/views/volunteering/time_entries/new_timesheets.js.erb





$('#box').html('<%= escape_javascript(render('new_timesheets', :@entries => @entries, :start => @start)) %>')


$('#records-table').dataTable({
        "bJQueryUI": true


});

app/views/volunteering/time_entries/show.html.erb
<h1 class="page-content corners-top">
  <%= Volunteering::Position.find_by_id(Volunteering::Record.find_by_id(@entry.record.id).position_id).name %>
  Position Time Sheet
</h1>

<div class="page-content corners-bottom">

  <h3>
    Week: <%= start = @entry.week.strftime('%Y/%m/%d') %> -
    <%= Date.parse(start).advance(:days => 6).to_time.strftime('%Y/%m/%d') %>
  </h3>


  <table class="width-100">
    <thead>
    <th class="ui-state-default"></th>
    <th class="ui-state-default">MON</th>
    <th class="ui-state-default">TUE</th>
    <th class="ui-state-default">WED</th>
    <th class="ui-state-default">THU</th>
    <th class="ui-state-default">FRI</th>
    <th class="ui-state-default">SAT</th>
    <th class="ui-state-default">SUN</th>
    </thead>

    <tr>
      <td>Hours</td>

      <% @entry_days.each do |ed| %>

          <% if @entry.id == ed.time_entry_id %>

            <td>
              <%= ed.hours %>
            </td>

          <% end %>



      <% end %>
    </tr>
  </table>

  <p>


    <%= om_button(:icon => 'clock') do %>
        <%=  link_to "Add Hours for Another Week", new_volunteering_time_entry_url(:id => @entry.record.id) %>
    <% end %>


  </p>

</div>

app/views/volunteering/time_entries/summary.html.erb
<% require_javascript 'thirdParty/jquery.dataTables.min.js' %>
<% require_javascript 'omega_volunteering_records' %>
<%# javascript_include_tag 'new_time_entry' %>
<% require_stylesheet 'omega_volunteering' %>
<% require_stylesheet 'thirdParty/jquery.dataTables.jui.css' %>

<div class="content circle-corners-bottom corners-top">
	<div class="heading-main">
		<h1 class="page-content">
  			Timesheet Summary
		</h1>
   </div>

   <div id="main-box">
   	<p>
	   	<strong>Week: <%= session[:week] %></strong>
		</p>

		<%= render 'timesheets_table' %>

 		<%= om_button(:contact => true, :icon => 'apply') do %>
         <%=  link_to 'Edit', all_timesheets_volunteering_time_entries_url(:id=> @position), :'data-tooltip' => 'Apply for this position' %>
		<%end%> 
   </div>
</div>