config/routes.rb
Omega::Application.routes.draw do
    #match 'calendars' => 'calendars#index'

	resources :accounts
	  
my_routes = lambda {
  resources :customizations do
    collection do
      put :reset_default
    end
  end
  resources :news_items do
    member do     
    end
    collection do
      get :fetch
      put :like
      put :dislike
      put :delete_keyword
      put :create_keyword
    end
  end
  resources :news_item_sources
  
  resources :calendars do
    resources :events
    resources :shares, :as => :calendar_shares, :module => :calendars
    collection do
      get :administer
    end
    member do
      get :share
    end
  end

  scope "/users/:user_id" do
    resources :calendars
  end


  #  resources :events
    resources :form_builders

  scope :path => 'contacts', :as => 'contact', :module => 'contacts' do
    resources :groups
    resources :households
    resources :organizations
    resources :skills do
      collection do
        get :suggest
      end
    end
	 resources :fields do
    	member do
			get :edit
		end
	 end
    resources :interests

    resources :imports do
      collection do
        match :csv_import_wizard, :to => 'imports#csv_import_wizard', :path => 'wizard/step/:step'
        post :update_csv
        get :undo_import
        get :get_import_data
        get :get_import_mapping
        get :undo_import_finalize
        get :redo_mapping
        get :delete_forever
        get :draft_import
        get :redo_import
        get :redo_import_finalize
      end
    end

  end

  resources :contacts do
    collection do
      get :all
      get :search
      get :list
      get :autocomplete
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end

    member do
      get  :upload
      post :do_upload
    end

    scope :as => 'contact', :module => 'contacts' do
      resources :groups do
        member do
          put :assign
          put :remove
          put :move, :path => 'move/:to_id'
        end
      end
    end
  end


  match 'contacts/:action' => 'contacts#search'

  resources :groups do
    #resources :topics
    member do
      get :space
    end    
  end
  resources :posts
  resources :topics
  resources :groups_requesters
  resources :groups_members do
    collection do
      post :add
      delete :remove
    end
  end
  
  resources :services   
  resources :service_sections
  resources :service_registrations do
    collection do
      post :paypal_return
      get :paypal_cancel_return
    end
  end
  
  resources :roles do
    collection do
      put :restore_role_permission_associations
    end
    member do
      put :update_permission
    end
  end

  resources :assets
  resources :asset_allocations

  resources :payments do
    collection do
      post :ipn_handler
    end
  end

  match 'reports/print_file' => 'reports#print_file'
  match 'reports/show' => 'reports#show'
  resources :reports

  namespace :volunteering do
    resources :positions do
      collection do
        get :scheduler
        get :upcoming
        get :mine
        get :my_time_sheets

        get :skills
        get :interests

        resources :skills, :only => [:index, :edit, :update, :destroy]
        resources :interests, :only => [:index, :edit, :update, :destroy]
      end

      member do
        get :history
      end
    end

    resources :schedules
    resources :days

    resources :records do
      collection do
        get :my_applications
        get :pending
        put :create_volunteer
        get :newest
        get :completed
        get :admin_page
        get :new_volunteer
        get :enroll_volunteers
		  post :create_single
		  put :update_status
        post :create_multiple
		  post :message_volunteer
        get :summary
        get :user_history, :path => 'user_history/:contact_id'
		  get :zip_search
      end

      member do
        get :administer
        get :withdraw
      end
    end

    resources :time_entries do
    	collection do
    		get :all_timesheets
    		get :new_timesheets
    		get :summary
    	end
    end



    root :to => 'volunteering#index', :as => ''
  end

  resources :favorites, :only => [:index, :show] do
    collection do
      match :add,    :path => 'add/*klass/:id',    :as => 'add_to'
      match :remove, :path => 'remove/*klass/:id', :as => 'remove_from'
    end
  end

  namespace :favorites do
    get :of_klass, :path => '*klass'
  end

  resources :uploads do

  end

  resources :images do
    collection do
   	get :edit_logo
   	put :update_logo
   end
  end

  resources :sessions do
    collection do
      delete :destroy
    end

    collection do
      get :token, :path => 'new/:token'
    end
  end

	resources :settings do
		collection do
			put :update
			get :edit
		end
	end

  resources :users do
	 member do
		get :my_page
		put :update_my_page
	 end
    collection do
      get :register, :check_email_uniqueness, :check_username_uniqueness
      post :join, :path => 'register'
      get :autocomplete
      get :role_assignment
      match :letter, :path => ':letter', :constraints => { :letter => /[a-z]/i }
    end
  end

  match 'lost_username' => 'users#lost_username'
  match 'lost_password' => 'users#lost_password'

  resources :roles
  resources :permissions, :only => [:index, :show]

  resources :messages, :except => [:edit] do
    collection do
      get :sent
    end

    member do
      get :reply
      get :forward
    end
  end

  root :to => 'home#index'

  scope :path => 'form_builder', :controller => :form_builder do
    get :dispatch_ui_element, :path => 'dispatch_ui_element/:element'
    get :dispatch_element_properties, :path => 'dispatch_element_properties/:element'
  end

  resources :pages, :glob_id => true do
    resources :blocks
    resources :components
  end
  resources :blocks
  resources :components

  scope :module => 'omega' do
    match '*url' => '#not_found'
  end
}

	# This allows us to use the /account_name in development.
	# If we used the subdomain, the account_name would be 
	# limited to the subdomain of your development server. 
	if Rails.env.development? or Rails.env.test?
		scope :path => "/:account_name" do
			my_routes.call
		end
	elsif Rails.env.production?
		my_routes.call
	end

end

app/models/report/position.rb
	class Report::Position
	  attr_accessor :name, :employee_names, :jobs, :total_hours
	
	  def initialize(name="", jobs=[])
	    @name = name
	    @jobs = jobs
	  end
	
	end

app/models/volunteering.rb
	module Volunteering
	  extend ActiveSupport::Autoload
	  
	  autoload :Position
	  autoload :Record
	  autoload :TimeEntry
	  
	  PERM_ADMIN            = 'volunteering_admin'
	  PERM_APPLY            = 'volunteering_apply'
	  PERM_ASSIGN           = 'volunteering_assign'
	  PERM_RECORD_HOURS     = 'volunteering_record_hours'
	  PERM_RECORD_OWN_HOURS = 'volunteering_record_own_hours'
	  PERM_VIEW             = 'volunteering_view'
	  
	  def self.table_name_prefix() 'volunteering_' end
	end

app/models/volunteering/contact_position.rb
	class Volunteering::ContactPosition < Model
	
	  belongs_to :contact
	  belongs_to :position
	  
	
	end

app/models/volunteering/day.rb
	class Volunteering::Day < Model
	
	  belongs_to :schedule
	
	
	end

app/models/volunteering/position.rb
	class Volunteering::Position < Model
	  include Calendar::Recurrence
	
	  MAX_POSITIONS_PER_PAGE = 5
	
	  has_many :contact_positions
	  has_and_belongs_to_many :contact_fields, :class_name => '::Contact::Field',
	  														 :join_table => 'contact_fields_volunteering_positions',
															 :foreign_key => :volunteering_position_id,
															 :association_foreign_key => :contact_field_id
	
	  has_many :contacts, :through => :contact_positions
	  
	#  belongs_to :contact
	  has_many :records, :dependent => :destroy, :inverse_of => :position
	  has_one :schedule
	
	  has_one :event_source, :as => :source, :class_name => '::Calendar::EventSource'
	  accepts_nested_attributes_for :event_source
	  
	  has_and_belongs_to_many :skills,    :class_name => 'Contact::Skill',
	                                      :join_table => 'contact_skills_volunteering_positions'
	                                     
	  has_and_belongs_to_many :interests, :class_name => 'Contact::Interest',
	                                      :join_table => 'contact_interests_volunteering_positions'
	
		accepts_flattened_values_for :skills, :interests, :value => :name
	  accepts_nested_attributes_for :schedule, :reject_if => proc { |att| att['start_time'].blank? }
	  accepts_nested_attributes_for :contacts
	
	#  attr_accessor :starttime_nr, :start_date_nr, :endtime_nr, :end_date_nr
	#
	#  before_save :combine_times
	
	#-------------------------------------------------------------------------------------------------
	
		validate :valid_dates
		validates_unique :name # Custom validation. See model.rb
		validates_presence_of :description, :volunteers_required, :name
		validates_numericality_of :volunteers_required, :only_integer => true, :greater_than => 0
		validates_presence_of :start, :end, :unless => :recurrent?
	
		def valid_dates
			self.errors.clear
			if !recurrent
				return 
				if start_time.nil? or end_time.nil?
					return self.errors.add :start_time, " The start time and end time must be filled in."
				end
				if start_time >= end_time
					self.errors.add :start_time, " The start time, #{start_time}, has to be before end time, #{end_time} "
				end
			elsif recurrent
				if recurrence_start_time.nil? or recurrence_end_time.nil?
					return self.errors.add :recurrence_start_time, " The start time and end time must be filled in."
				end
				if recurrence_start_time >= recurrence_end_time
					self.errors.add :recurrence_start_time, " #{recurrence_start_time} has to be before end time, which is #{recurrence_end_time}"
				end
			end
		end
	
	#-------------------------------------------------------------------------------------------------
	
	  def active_volunteers
	    records.includes(:contact).where('action = ?', 'Accepted').collect(&:contact)
	  end
	
	  def unrejected_volunteers
	    records.includes(:contact).select { |r| r.action != 'Rejected' }
	  end

	  def missing_volunteers
	    volunteers_required - active_volunteers.count
	  end
	
	  def to_s
	    "Volunteering Position: #{name}"
	  end
	
	  def to_param
	    "#{id}-#{name.parameterize}"
	  end
	
	  def status_of(contact)
	    if record = record_for(contact)
	      :valid
	    else
	      :none
	    end
	  end
	
	  def record_for(contact)
	    contact.nil? ? nil : records.where('contact_id = ?', contact).first
	  end
	
	  def start_date
	    start.try(:to_date)
	  end
	
	  def start_date=(value)
	    self.start = "#{value} #{start_time}"
	  end
	
	  def start_time
	    start.try(:to_s, :time)
	  end
	
	  def start_time=(value)
	    self.start = "#{start_date} #{value}"
	  end
	
	  def end_date
	    self.end.try(:to_date)
	  end
	
	  def end_date=(value)
	    # self.end = "#{value} #{end_time}"
	    # FIXME!!!!!!
	    self.end = "#{start_date} #{end_time}"
	  end
	
	  def end_time
	    self.end.try(:to_s, :time)
	  end
	
	  def end_time=(value)
	    # self.end = "#{end_date} #{value}"
	    # FIXME!!!!!!
	    self.end = "#{start_date} #{value}"
	  end
	
	  def correct_end_date
	  	s = self.start
	  	e = self.end
		s_mins = (s.hour * 60) + s.min
		e_mins = (e.hour * 60) + e.min
		difference_in_seconds = 60 * (e_mins - s_mins)
		s + difference_in_seconds
	  end

    def duration
      return self.end-self.start if not recurrent
	  	return next_recurrence.to_time.to_i - recurrence_start.to_time.to_i if recurrent
    end

		def next_occurence
			recurrent ? next_recurrence : start
		end

		def next_recurrence
			recur = recurrences
			recur.each do |r|
				return r if r >= Date.today
			end
			recur.last # Return last event if no recurrence happens after today
		end

		# return an array of all recurrences
		def recurrences
			recurrence_end_on == 'number' ? recurrences_for_end_number : recurrences_for_end_date
		end

		def recurrences_for_end_date
			all = [recurrence_start]
			case recurrence_pattern
				when 'weekly'
					until recurrence_end_at < (all.last + 7)
						all << (all.last + 7)
					end
				when 'monthly'
					until recurrence_end_at < (all.last >> 7)
						all << (all.last >> 1)
					end
				when 'yearly'
					until recurrence_end_at < (all.last >> 12)
						all << (all.last >> 12)
					end
			end
			all
		end

		def recurrences_for_end_number
			all = [recurrence_start]
			case recurrence_pattern
				when 'weekly'
					(recurrence_end_after - 1).times do
						all << (all.last + 7)
					end
				when 'monthly'
					(recurrence_end_after - 1).times do
						all << (all.last >> 1)
					end
				when 'yearly'
					(recurrence_end_after - 1).times do
						all << (all.last >> 12)
					end
			end
			all
		end


		class << self

			# Return all positions that haven't already passed.
			def active
				all.select { |vp| vp.next_occurence.to_date >= Date.today }
			end

			def rank
				positions = active
				time_weight = 1.5
				priority_scores = { 'Urgent!' => 1.0, 'High' => 0.5, 'Normal' => 0.0 }
				time_rank = positions.sort_by { |vp| vp.next_occurence.to_date }.reverse
				scores = {}
				c = count.to_f - 1
				time_rank.each_with_index do |vp, i|
					normalized = (i/c * time_weight)
					priority = (priority_scores[vp.priority] or 0.0)
					scores[vp] = (normalized + priority)
				end
				scores = scores.sort_by { |k,v| v }.reverse
				scores.inject([]) { |array, subarray| array << subarray.first }
			end

		end
	
	
	end
	
	class Volunteering::Position::CollectionWithAll
		def name
			"All Positions"
		end
	
		def id
			Volunteering::Position.find(:all).collect { |vp| vp.id }.join(',')
		end
	end
	
	class Volunteering::Position::CollectionWithCurrentPosition
		def name
			"This Position Only"
		end
	
		def id
			0
		end
	end

app/models/volunteering/record.rb
	class Volunteering::Record < Model
	
	  MAX_RECORDS_PER_PAGE = 100
	
	  belongs_to  :position, :inverse_of => :records
	  belongs_to  :contact
	  has_many    :time_entries, :dependent => :destroy
	  
	  before_validation( :on => :create) do
		 self.status = "Applied"
	  end
	
	  default_scope order('created_at desc')
	
	  validate :contact_has_only_one_record_per_position
	  #validates :status, :presence => true,
	                     #:inclusion => { :in => [:applied, :declined, :accepted] }
		def contact_has_only_one_record_per_position
			self.errors.clear
			if self.new_record?
				contact_records = Volunteering::Record.where('contact_id = ?', self.contact_id)
				contact_records.each { |r| contact_records.delete(r) if r.id == self.id }
				records_for_this_position = contact_records.select { |r| r.position_id == self.position_id }
				if records_for_this_position.count > 0
					self.errors.add :contact_id, 'This user already has a record for this position.'
				end
			end
		end
	
	
		class << self
			def for(user)
				Volunteering::Record.all.select { |vr| !vr.contact.nil? }.select { |vr| vr.contact.user == user and vr.status != "Rejected" }
			end
	
			def sort_by_selected_position(records, record_id)
				return records if record_id.nil?
				record_id = record_id.to_i
				sorted_records = records.select { |r| r.id == record_id }
				records.each { |r| sorted_records << r unless r.id == record_id }
				sorted_records
			end

			def find_by_contact_and_position(contact, position)
				records = Volunteering::Record.all
				records.select! { |r| r.contact.id == contact.id and r.position.id == position.id }
				records.empty? ? nil : records.at(0)
			end
		end
	
	
		def position_name
			self.position.name
		end
	
	end

app/controllers/volunteering/days_controller.rb
	class Volunteering::DaysController < Controller
	  respond_to :html, :xml, :json, :js
	  require_permission Volunteering::PERM_VIEW
	  require_permission Volunteering::PERM_ADMIN, :only => [:new, :edit, :create, :update, :destroy]
	
	  def index
	      @days = Volunteering::Schedule::Day.all
	      respond_with(@days)
	    end
	
	    def show
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      respond_with(@day)
	    end
	
	    def new
	      @day = Volunteering::Schedule::Day.new
	      respond_with(@day)
	    end
	
	    def edit
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      respond_with(@day)
	    end
	
	    def create
	      @day = Volunteering::Schedule::Day.create(params[:volunteering_schedule_day])
	      respond_with(@day)
	    end
	
	    def update
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      respond_with(@day)
	    end
	
	    def destroy
	      @day = Volunteering::Schedule::Day.find(params[:id])
	      @day.destroy
	           
	    end
	  end

app/controllers/volunteering/interests_controller.rb
	class Volunteering::InterestsController < Controller
	  respond_to :html, :json
	
	  def index
	    @interests = Contact::Interest.scoped
	
	    @interests = @interests.where("name LIKE ?", params[:q] + '%') if params[:q]
	
	    respond_with(@interests) do |format|
	      format.json { render :json => @interests.map { |s| { :id => s.name, :name => s.name } } }
	    end
	  end
	end

app/controllers/volunteering/skills_controller.rb
	class Volunteering::SkillsController < Controller
	  respond_to :html, :json
	
	  def index
	    @skills = Contact::Skill.scoped
	
	    @skills = @skills.where("name LIKE ?", params[:q] + '%') if params[:q]
	
	    respond_with(@skills) do |format|
	      format.json { render :json => @skills.map { |s| { :id => s.name, :name => s.name } } }
	    end
	  end
	end

app/controllers/volunteering_controller.rb
	class VolunteeringController < Controller
	  require_permission Volunteering::PERM_VIEW
	
	  def index
	
	  end
	end

app/views/volunteering/positions/_contact_form.html.erb
<%= div_for f.object do %>
    <%= errors_for_model f.object %>

       <p>
			<%= f.label :title %>
			<%= f.select :title, options_for_select(Contact::TITLES) %>
       </p>

        <p>
            <%=f.label :first_name %>
            <%= f.text_field :first_name %>
        </p>

        <p>
            <%=f.label :last_name %>
            <%= f.text_field :last_name %>
        </p>
         <p>
            <%=f.label :email %>
            <%= f.text_field :email %>
        </p>



        <%= f.fields_for :phone_numbers do |fff| %>
            <%= render 'phone_form', :f => fff %>
        <%end%>

<%end%>

app/views/volunteering/positions/_form.html.erb
<% require_stylesheet 'omega_volunteering' %>
<% require_javascript 'thirdParty/jquery.timepicker', 'new_volunteering_position', 'jquery.tokeninput' %>

<div id="assignment">              </div>

<%= form_for(@position, :html => {:id => 'volunteer_position_form'}) do |f| %>
    <%= errors_for_form(@position, 'position') %>
     
	  <h3 class="application-form">Assignment Detail</h3> 
 
	  
	   <p>
        <%= f.label :name %>
        <%= f.text_field :name, :'data-tooltip '=> 'descriptive name for position', :class => 'broad-text' %>
      </p>

      <p>
        <%= f.label :description %>
        <%= f.text_area :description, :rows => 6, :'data-tooltip '=> 'describe what work the volunteer will be doing in this position', :class => 'broad-text' %>
      </p>
      
      <p>
        <%= f.label :volunteers_required %>
        <span data-tooltip="Increase" class="om-icon-only om-blue-icon ui-icon-plusthick increase"></span>
        <%= f.text_field :volunteers_required,:value => 1,:class => "inputSmall" %>
        <span data-tooltip="Decrease" class="om-icon-only om-blue-icon ui-icon-minusthick decrease"></span>
      </p>

		<p>
			<%= f.label :priority%>
			<% ['Normal','High', 'Urgent!'].each do |p|%>	
				<%= f.radio_button :priority, p%> <%=p%>
			<%end%>
		</p>
      <br/>

      <p>
        <%= f.label :reoccurs %>
        <%= f.radio_button :recurrent, true %>
      </p>
      
      <p>		
        <%= f.label :one_time_only %>
        <%= f.radio_button :recurrent, false %>
      </p>

      <div id="non_recurrent" <%= %q{style="display:none;"}.html_safe if @position.recurrent? %>>
        
        <h3 class="application-form">Timeline</h3> 

        <p>
          <%= f.label :date %>
          <%= f.text_field :start_date, :class=>'datepickr', :autocomplete => 'off' %>
        </p>

        <p>
          <%= f.label :start_time %>
          <%= f.text_field :start_time, :class=>'tpickr', :autocomplete => 'off' %>
		  </p>
		
		  <p>
          <%= f.label :end_time %>
          <%= f.text_field :end_time, :class=>'tpickr',  :autocomplete => 'off' %>
        </p>
      </div>

	    <%= render('shared/recurrence', :builder => f, :hidden => !@position.recurrent? ) %>

    
  	 <h3 class="application-form">Calendar Synchronization</h3> 

    <div class="helptext">
      By checking the selectbox below and choosing a calendar you can make this volunteering position to appear in the selected calendar
    </div>

	 <%= f.fields_for :event_source do |es| %>
   	<%= es.label :'synchronize?' %> <%= es.check_box :synchronize %><br/><br/>
		<%= es.label :'Calendar' %> <%= es.select :calendar_id, options_from_collection_for_select(Calendar.scoped, :id, :calendar_name, es.object.calendar_id) %>
    <% end %>

    <div id="vp_contact">
       <h3 class="application-form">Contact for this position</h3> 
        <% [['none', 'no contact'], ['existing', 'existing contact']].each do |value, text| %>
				<% checked = value == @contact_assignment ? {'checked' => true} : nil %>
            <%= radio_button_tag 'contact_assignment', value, checked %><%= text %>
        <% end %>

     <div id="position_existing_contact" class="hide">
        <h2 class="application-form-content-heading">Assign Exisiting Contact</h2>
        <table>
          <tr>
            <td><%= f.label "contact_name(s)" %></td>
            <td>
              
              <span id="add-contacts">
                <span class="om-icon-only om-blue-icon ui-icon-plus" data-tooltip="Add contact"></span>
                Add an existing contact
              </span>

              <ul id="assigned_contacts" style="margin-left:-120%">
                <% @position.contacts.each do |c| %>
                    <li ui-data="<%= c.id %>">
                      <span class="om-icon-only om-blue-icon ui-icon-minus" data-tooltip="Remove this contact"></span>
                      <%= c.first_name %><%= c.last_name %>
                    </li>
                <% end unless @position.contacts.empty? %>
              </ul>

            </td>
          </tr>
        </table>
        <%= f.hidden_field :contact_ids %>
    	</div>
	


      <h3 class="application-form">Custom Field</h3>
			<p> You can customize the application form that volunteers fill out when they apply to this position.  Just select the questions below that you want volunteers to answer when they apply to this position.  You can always add or remove these questions later by clicking the Edit Position button. </p>
			<% fields = Contact::Field.all %>
			<%= f.fields_for :contact_fields, fields do |cf| %>
				<table id="custom_field_checkboxes">
					<% fields.each_with_index do |cc, index| %>
						<%= "<tr>".html_safe if (index % 5) == 0 %>
							<td>
								<p><%= check_box_tag "volunteering_position[contact_fields[#{index}]]", cc.id, @position.contact_fields.include?(cc) %> <%= cc.name.to_s %></p>
								<p><%= cc.description %></p>
							</td>
						<%= "</tr>".html_safe if (index % 5) == 4 %>
					<% end %>
				</table>
			<% end %>
				


      <h3 class="application-form">Skills and Interests</h3>
      <p>
        <%= f.label :skills %>
        <%= f.text_field :skills_values%>
      </p>

      <p>
        <%= f.label :interests %>
        <%= f.text_field :interests_values%>
		</p>
	
		<p>
			<%= f.label :disclaimer_agreement%>
			<%= f.radio_button :disclaimer_agreement, true, :checked => @position.disclaimer_agreement %> Required <br/>
			<%= f.radio_button :disclaimer_agreement, false, :checked => !@position.disclaimer_agreement %> Not Required <br/>
		</p>
		
		<div id="agreement">
			<p>
				<%= f.label :agreement_detail%>
				<%= f.text_area :agreement%>
			</p>
		</div>
		
	   <p>
	      <%= om_button(:icon=>'save') do %>
	   	   <%= f.submit %>
	      <% end %>
		</p>

<% end %>

app/views/volunteering/positions/_form_schedule_daily.html.erb
<fieldset id="daily_schedule" class="hide">
  <legend> daily schedule</legend>
  <h4> Please select when this event occurs</h4>
  <%= f.fields_for :schedule do |s| %>
  <%= s.fields_for :daily do |d| %>

      <%= radio_button_tag 'daily_type', 'every_week_day' %>Every weekday

      <br>

      <%= radio_button_tag 'daily_type', 'every_day' %>Every <%= d.text_field :value, :size=>2 %> days

      
      <p>
        <%= d.label :start_time %>

        <%= d.text_field :start_time, :id=> nil, :class=>'tpickr', :size=>7 %>
      </p>

      <p>
        <%= d.label :end_time %>

        <%= d.text_field :end_time, :id=> nil, :class=>'tpickr', :size=>7 %>
      </p>
      <h4>Please select the range of occurences</h4>

      <p>
        <%= d.label :start_date %>
        <%= d.text_field :start_date, :id => nil, :class =>'datepickr', :size=>7 %>
      </p>

      <p>
        <%= d.label :end_date %>
        <%= d.text_field :end_date, :id => nil, :class=>'datepickr', :size=>7 %>
      </p>
    <% end %>


  <% end %>
</fieldset>


<div id="weekly">

</div>

app/views/volunteering/positions/_interest_form.html.erb
<%= div_for f.object do %>
    <%= errors_for_model f.object %>

        <p>
            <%=f.label :interests %>
            <%= f.text_field :name %>
        </p>



<%end%>

app/views/volunteering/positions/_phone_form.html.erb
<%= div_for f.object do %>
	
   <p>
		<%= f.label :number_type %>
		<%= f.select :number_type, options_for_select(Contact::PhoneNumber::NUMBER_TYPES) %>
	</p>

   <p>
		<%= f.label :number %>
		<%= f.text_field :number %>
	</p>

<% end %>

app/views/volunteering/positions/skills.html.erb
<% require_stylesheet 'omega_volunteering' %>

    <div class="content circle-corners-bottom-left">
    	
		<div class="heading-main-columns">
	
				<h1 class="page-content">
      				Current Volunteering Opportunities
		    	</h1>
	
		</div>


      <div class="right">
      	<br/>
        <%= om_button(:icon=>'sort-az', :small => true) do %>
            <%= link_to 'sort A-Z', url_for(params.merge(:name => 'asc')) %>
        <% end %>
        <%= om_button(:icon=>'sort-za', :small => true) do %>
            <%= link_to 'sort Z-A', url_for(params.merge(:name => 'desc')) %>
        <% end %>

      </div>

      <div class="clear"></div>

      <% if tags = @skills_tags or tags = @interests_tags %>
          <p>
            <% tags.each do |tag| %>
                <%= link_to nil, tag, :class => 'skill-tag-active' do %>
                    <span> <%= tag %> </span>
                <% end %>
            <% end %>
          </p>
      <% end %>
      
      <ul id="positions-list">
        <% @positions.each do |position| %>
            <li id="position-<%= position.id %>">
              <div class="position-slider">
                <%= render 'volunteering/positions/partials/position_actions', :position => position %>
              </div>
              <div class="position">
                <div class="position-wrapper">

                  <% if position.start? %>
                      <div class="pos-date">
                        <div class="pos-cal-month">
                          <%= position.start.strftime("%b") %></div>
                        <div class="pos-cal-day"> <%= position.start.day %></div>
                      </div>
                  <% else %>
                      <div class="pos-recurrent">
                        <div class="posCalMonth">

                        </div>

                        <div class="posCalDay"></div>
                      </div>
                  <% end %>
                  <h2>
                    <%=  link_to truncate(position.name, :length=>60), volunteering_position_path(position), :class => 'position-name'  %>
                  </h2>

                  <p>
                    <%= truncate(position.description, :length=> 140) %>
                  </p>

                  <p>
                    <%=  link_to '( read more ... )', volunteering_position_path(position) %>
                  </p>
              <span>
                <% position.skills.each do |skill| %>


                     <%= link_to volunteering_skills_path(:skills => [params[:skills], skill.name].compact.join('+')), :class => 'skill-tag' do %>
                           <span class="skill-tag"> <%= skill.name %>  </span>
                        <% end %>


                <% end %>
                <div class="clear"></div>
              </span>
                </div>
              </div>
              <div class="clear"></div>
            </li>
        <% end %>
      </ul>
      <%= will_paginate @positions %>
      <div class="clear"></div>
    </div>

<% content_for :sidebar do %>
    <%= render :partial => "layouts/sidebar_positions_skills" %>
    <%= render :partial => "layouts/sidebar_positions_interests" %>
<% end %>